    export const GET_COMICS= 'GET_COMICS';
    export const SEARCH_COMICS= 'SEARCH_COMICS';
    export const GET_COMIC_BY_NAME= 'GET_COMIC_BY_NAME';
    export const PAGINATE_COMICS= 'PAGINATE_COMICS';
    export const APPLICATION_LOADING= 'APPLICATION_LOADING';
